name: Test Apply Resources
on:
  workflow_dispatch:  # Allow manual triggering
  push:
    branches:
      - main
      - release/*
      - snapshot/*
    tags:
      - v*
  pull_request:
  merge_group:
jobs:
  test-apply-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install percli
        uses: ./actions/install_percli
        with:
          cli_version: "latest"

      - name: Login to the API server
        uses: ./actions/login
        with:
          url: https://demo.perses.dev
          username: test
          password: test

      - name: Test apply resources
        uses: ./actions/apply_resources
        with:
          file: ./testdata/resources_folder/dashboard.json

